"""empty message

Revision ID: 7e3480cb9b3a
Revises: 
Create Date: 2021-07-05 21:22:56.038800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e3480cb9b3a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teama',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('a_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teamb',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('worka',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('teama_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['teama_id'], ['teama.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_table('workb',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('teamb_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['teamb_id'], ['teamb.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workb')
    op.drop_table('worka')
    op.drop_table('users')
    op.drop_table('teamb')
    op.drop_table('teama')
    # ### end Alembic commands ###
